### ISSUE TITLE
Make it possible to count non-files

### ISSUE THREAD

**Issue by agross** [palantir/gulp-count#1]
...e.g. in-memory files created with https://github.com/alexmingoia/gulp-file. Currently these files will not be counted (no totals). You should of course omit logging the file.

**Comment by giladgray** [comment]
Yeah I've been thinking about how to deal with this, because the file check clearly isn't a good thing. I've got a few thoughts about direction here:

1. remove the check and just count everything that comes down the stream, but then directories in globs are included,
2. support a `filter` option, but that might be too much functionality.
3. something along the lines of `filesOnly` flag.

**Comment by agross** [comment]
I think #1 with #2 is the most flexible approach. You could supply predefined functions like gulp-changed does.

**Comment by giladgray** [comment]
Just removed the `isFile()` check so this issue may be resolved...

#oneyearlater
